### ISSUE TITLE
Open links without confirmation

### ISSUE THREAD

**Issue by hasinasi** [te-online/files_linkeditor#11]
I find these links quite useful even to jump to different folders within the cloud. For that it would be useful to have some kind of option that links would be opened without the confirmation dialog. Perhaps for links within the cloud? Or for links to a certain domain (or certain domains)? Or for all links?

**Comment by te-online** [comment]
This is what I wanted from the start, but limitations popped up during development. 

Unfortunately, it is not trivial from a technical point of view. The app reads the URL from the file to make sure links can also be synced via the Desktop client and to have a persistent and standard-conform way to save and retrieve the links. 

Currently, this requires an AJAX request to be fired to read the file from the server and then present you with the URL and a possibility to visit the URL. When I were to redirect you directly to that URL or open it in a new window, after doing an AJAX request, this would be an asynchronous change of context. The browser will then interpret this as an unwanted pop-up and hence completely block it. 

In English: I already need to know the target URL when you click on the link in the filelist to convince the browser that it is your intention to visit this URL. I can't get to the URL without reading the file. This means, I need to have some kind of cache of the URLs when a filelist is loaded. While it sounds easy, a cache could potentially be extremely error-prone and introduce all kinds of side-effects.

As a user-friendly alternative, I simply implemented the little window, telling you which URL you're about to visit, which also adds transparency to what is going on. But of course is not very intuitive or quick for some use-cases.

I'll flag this as an enhancement and keep it in the list, but, unfortunately, I have to say, don't expect a solution anytime soon. (Unless, you find a way yourself and make a pull request 😉.)

**Comment by te-online** [comment]
### General summary of the issue for readers visiting at a later point
This issue resolves around a fundamental design problem when implementing this app. This app loads and parses the linkfile on the client-side. But while a browser can be instructed to load a file (an asynchronous action), parse its contents and then open a link in a new window, this behavior is (rightfully so) interpreted as something that's commonly know as “pop up-window” and blocked in most modern browsers. Opening new windows/tabs has to be triggered immediately after user interaction (e.g. clicking a button) – no time to load and read the linkfile.

Settling on a compromise, the confirmation dialog was introduced, allowing the app to load and read the file and then offering a button that can trigger the link action directly.

From version 1.1.0 this dialog will be skip-able, if the link opens in the same window, because asynchronously navigating within the same window is not blocked as a pop up.

### Outlook / Future planning 
There is a way to implement opening the linkfile without confirmation and in a new window/tab. It can be achieved by linking to a route on the Nextcloud instance that then parses the linkfile and redirects to the target link. That way the link will look innocent to the browser and the redirect will take place server-side. However, considerable effort is connected to this implementation, because both file-parsers need to be re-written and a server-side route needs to be established.
