### ISSUE TITLE
Describe how to open .url files on Linux desktop

### ISSUE THREAD

**Issue by rasos** [te-online/files_linkeditor#25]
What is the best strategy to open a .url file in Thunar or Nautilus? 

[This proposal](https://saidulhassan.com/open-url-files-in-linux-mint-ubuntu-1029) as a custom script for url file types does not really work properly, firefox loops downloading the file:

 `bash -c “cat %f | grep URL | cut -d’=’ -f2 | xargs firefox &”`

**Comment by te-online** [comment]
Thanks for your thoughts on opening link files on Linux. I don't think it's this app's responsibility to explain how to use a specific feature of a Linux Desktop. As far as I know, on some distribuitions you can use custom shortcuts on your Desktop, but I don't know of any that allow you to open .URL or .webloc files. For commandline use, your script doesn't look that bad. It should open the URL that is stored within a URL file, referenced by `%f`. Does it do something else for you? 

Aside from that I think this app could be enhances in terms of operating system support. We should not only enable to create .URL files, but also other kinds of files that can store links. And maybe also the Desktop client could be adjusted to associate with .URL files and open them in a browser.

But these are just some thoughts and while I can write them down here, I have to pass on implementing them right now due to missing time resources on my end.

Therefore I'll close this issue for now. However, if you have any specific suggestions to enhance the Readme file or concepts to add better operating system support, feel free to open another issue or even a pull request. I'll happily review them 🙂
