### ISSUE TITLE
Can't open synced .url files from mobile app

### ISSUE THREAD

**Issue by julianfinn** [te-online/files_linkeditor#44]
Hi, I've managed to get .url files synced to a nextcloud folder and those links work perfectly from a desktop browser. The issue I'm running into is that when users attempt to use those links from within the iphone app, iOS has no idea what to do with them. When I try to share the link to Chrome (which is the only browser that even shows up as an option in the share dialog) it errors out and says it can't handle the file.
![150939092_359609831691159_2505378786275592385_n](https://user-images.githubusercontent.com/79289790/108438008-a138e800-720b-11eb-9d8b-f9ea23c882ea.jpg)

**Comment by te-online** [comment]
Hey @julianfinn Glad you were able to sync link files with Nextcloud and that you enjoy the app.

Unfortunately, I don't know of any way to tell the mobile Nextcloud app how to handle link files. 😞 

That's why I need to direct you to the repository of the [iOS Nextcloud app](https://github.com/nextcloud/ios), where you might be able to open an issue asking for this feature. Maybe they will be able to tell you what the Linkeditor Nextcloud app can do to help with that.
