### ISSUE TITLE
In Firefox new link opens only after cache cleaning

### ISSUE THREAD

**Issue by robshnup** [te-online/files_linkeditor#47]
In FF 86, when you create a new url and want open it subsequently it fails with the message:

> Diese Link-Datei scheint nicht lesbar zu sein. – Du kannst die Datei durch Bearbeiten reparieren.

FF shams that nothing has been saved as URL - the link field is empty. 
Only after a complete cache-cleaning everything is OK. The link was saved and can be opened.

In Chrome there is no hassle.

Greetings robw

**Comment by te-online** [comment]
Does this happen to you with other apps, too? Maybe your server's caching headers are a little agressive?
I just tried in Firefox 86 on Mac but couldn't reproduce 🤔 (see video)


https://user-images.githubusercontent.com/4127167/111805936-c3d52400-88d1-11eb-968e-d60ba50345bb.mov


Any chance you can provide the exact steps that will reproduce the issue?

**Comment by robshnup** [comment]
Hi,
I fail to see why server's caching headers are too agressive, because in that case there would be the probs in Chrome too.
With other apps of Nextcloud there are no probs whatsoever.

I'm here with FF86 on Debian Bullseye and Nginx 1.18, PHP7.4-fpm
Where the nextcloud nginx cache config cache proposes 6M

>     location ~ \.(?:css|js|svg|gif)$ {
        try_files $uri /index.php$request_uri;
        expires 6M;         # Cache-Control policy borrowed from `.htaccess`
        access_log off;     # Optional: Don't log access to assets
    }

I have 21d

> location ~ \.(?:css|js|woff2?|svg|gif|map)$ {
    try_files $uri /index.php$request_uri;
    expires 21d;
   access_log off;
   }

That's all I can say. "My exact steps" are very simple: Make a new URL -> copy the link -> Save -> Prove -> Receive error
The proof with the button "visit link" works good in every case. But afterwards in FF the address-line is empty. I can refill the link, but it works only after a cache-clean. Then address-line is ok.
In Chrome and Edge everything's Ok from beginning.

**Comment by te-online** [comment]
That was just a guess about caching headers 😉 I think your problem might be something else.
Would it be possible for you to take a screengrab of the steps? I'm afraid I can't follow 🙈 Where are you copying a link?

**Comment by robshnup** [comment]
Hi, 
First I open a new link and enter the link-address oder paste it from clipboard
![grafik](https://user-images.githubusercontent.com/80580927/111867417-09e2c400-8974-11eb-9e63-60c6f3f24947.png)
then i prove the link by clicking on "Link besuchen"
If everything is ok then I press "Speichern". And then I get this screen:
![grafik](https://user-images.githubusercontent.com/80580927/111867468-6a720100-8974-11eb-98d2-3a174e916d1a.png)
Afterwards by clicking on "Link bearbeiten" I get this screen with link address empty
![grafik](https://user-images.githubusercontent.com/80580927/111867510-bcb32200-8974-11eb-9719-a65752e6082f.png)

And the game goes on and on till I make a cache-clean

**Comment by robshnup** [comment]
https://user-images.githubusercontent.com/80580927/111868934-351de100-897d-11eb-9932-fe61a6fe68ad.mp4

**Comment by te-online** [comment]
Thanks a lot for providing those details 🙌 
I think I understand the nature of your issue now. Not sure of the underlying cause, however.

It's almost as if the file is not saved correctly until you reload? This sounds like maybe some unrecoverable JavaScript error when you save the file, so subsequent reads fail because of that. When you reload the page, this JavaScript error is cleared and you can open the file fine. That's my best guess, because the file seems to be saved fine when you reload the page. Reloading the page doesn't do anything to help saving the file, leaving only two options for why reloading fixes the error:

1. The file is saved correctly, but the script for opening the file is unable to open it in the same "session" immediately after saving
2. The file is saved with a delay, making it appear that you can only open it after a refresh, when it's actually a timing issue (are you using an external storage of some kind that could delay saving file contents?)

I think 1 is the most likely case here.

That's why I'm going to ask you to collect more info from your browser when the read error occurs (that is, when you open the file and it seems corrupted). You can open the developer console of Firefox by clicking anywhere on the page and clicking "Inspect element" ("Element untersuchen" in the German version?). Then try and find the "Console" tab. Now try and create and open a file like you do in the screengrab. Then copy and paste any errors (red text) or anything else that looks suspicious from the console into this thread or take a screenshot of it and post it.

Sorry this is such a hassle to debug, but this additional info would help a great deal 🤷

**Comment by robshnup** [comment]
Hi Thomas,
it seems jinxed! And I think it's a timing prob.

If I use the console, it seems that saving lasts a small bit longer than without. And tadaa! - no hassles, the link opens instantly.
(There are btw. only a lot of warnings in console concerning JQuery and nothing seems relevant for my prob.
> 14:49:41.472 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 14 globals.js:60:15
14:49:48.981 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 16 globals.js:60:15
14:49:49.155 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
)

And - here it reveals - without console I have to wait about half a minute and the link gets OK. If you take a closer look at my little video: on the right there is after saving a remark: "in ein paar sekunden". I think it needs some time to save it in reality. But I don't use external storage devices. And it wouldn't also be accountable why Chrome has not that prob like FF?!

**Comment by te-online** [comment]
That sounds very curious 🤔 It's almost like Nextcloud returns with a positive result on the file being stored when it's actually still being written or something like that. Just to clarify, which version of Nextcloud are you using and can you share anything about your setup (like is it a vserver, a server in your home, HDD vs. SSD, is it a raspberry pi)?

**Comment by robshnup** [comment]
As I'v already written:
I'm here with FF86 Windows 10 Pro  on PC and on a Thinkpad i5-8250U CPU with 16GB
Server is (no PI) a 4GB RAM, Intel Atom 4-Cores with Debian Bullseye 5.10.0-4-amd64 (SMP) x86_64 and Nginx 1.18, PHP7.4-fpm
dedicated to Nextcloud. Ext4-FS on Normal 500GB HDD, GBit Ethernet

**Comment by robshnup** [comment]
Another further inquiry:
I must revoke my statement, that with console a link is working instantly. From my Notebook (Wlan??) it lasts also 1 minute till it works.
At the moment of saving a link these are all the messages in console:

> 17:01:07.986 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:15
17:01:16.724 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 328 globals.js:60:15
17:01:30.685 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:15
17:01:31.115 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:15
17:01:31.392 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 12 globals.js:60:15
17:01:31.398 OC.Util.formatDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment util.js:121:11
17:01:31.399 OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment util.js:133:11
17:01:31.399 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 12 globals.js:60:15
17:01:31.412 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:15
17:01:31.413 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 2 globals.js:60:15
17:01:31.679 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 40 globals.js:60:15
17:01:32.208 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 312 globals.js:60:15
17:01:35.818 OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment util.js:133:11
17:01:37.814 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 4 globals.js:60:15
17:01:37.995 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 7 globals.js:60:15

And last but not least: If NC indicates at right column "geändert" -> "gerade eben" -> the link will not work.
After a minute it indicates "vor 1 Minute" -> and voilà it works.

**Comment by te-online** [comment]
Quick update: I received your info, but it still doesn't ring a bell. I will need to dig a little deeper with the information you gave me and will get back to this issue. Thanks for your patience 🙏

**Comment by robshnup** [comment]
Don't mention it! I must thank you for your investigative drive ... ;-)

**Comment by te-online** [comment]
@robshnup I just came back to this part of your comment:

> Nextcloud log reports frequently

>> [files_linkeditor] Error: File: /Privat/sz.URL modified since opening.
>>    PUT /apps/files_linkeditor/ajax/savefile
>>    from 79.212.xxx.xx by rob at 2021-03-20T13:45:04+00:00

If I look at the backend controller (this is some code adapted from `files_texteditor`), it should actually return an API error response and not save the file. https://github.com/te-online/files_linkeditor/blob/master/controller/linkhandlingcontroller.php#L162

But from the browser console logs you posted, it doesn't look like you've received any error response for the PUT request of initially saving the file? And then after a while the file is actually saved? The message in your log does seem to refer to your problem, but doesn't entirely explain what's going on. 

Could I ask you to try and watch the nextcloud log and browser console while you create a link file and see if 
(1) there is a "modified since opening" error in the Nextcloud log?
(2) there is a failed PUT request in your Network tab of the browser console?

Then, since this sounds like it is related to timezone settings, could you check the timezone settings of your machine, of PHP (php.ini) and maybe ngnix if there is any timezone related config there?

**Comment by robshnup** [comment]
I'll investigate this tomorrow and make a report.
Thanks for your inquiry.
Greetz

**Comment by robshnup** [comment]
Hi,
I've made a test link in FF and watched the network console.
If I prevent to call the cache it lasts more than 10 seconds to save the link, but it works immediately.
![Zwischenablage-1](https://user-images.githubusercontent.com/80580927/115500436-8e757a80-a271-11eb-8146-442c19407d50.jpg)

With caching I get this result
![Zwischenablage-2](https://user-images.githubusercontent.com/80580927/115500498-aea53980-a271-11eb-92cc-db8ff08c342e.jpg)


Here it lasts only a bit under 2 seconds.
And - yes - in second case there is a "modified since opening" error in the Nextcloud log!
There aren't any errors in php.log in any case! 
Server timezone is "Europe/Berln" - no additional timezone.settings in nginx.

**Comment by te-online** [comment]
@robshnup There are two things that I observe that look strange to me:
- Your server seems to take very long to save a new, empty file (this app is using Nextcloud's built in functions here, so it should take as long to create, let's say, an .odt file or .txt file. Is that true?)
- Your configuration allows to load Ajax responses from cache (which is unusual in my eyes, but might be intended in tuned Nextcloud setups, I'm unsure)

However, I just inspected this on my own Nextcloud instance – by no means a perfect setup, but this original error does not happen there – and I receive a no-cache header. I'm pasting the headers below. From what I can see in your screenshots, it would seem that Firefox thinks it is allowed to take the ajax `GET` response from its cache. Which doesn't sound like a good idea, because ajax requests often don't return the same result even for the same URL + set of parameters. Especially after creating the file, it shouldn't have anything in cache at all, because the file didn't exist before!?

`GET /index.php/apps/files_linkeditor/ajax/loadfile?filename=test 2.URL&dir=/Documents`
Response Headers 👇 
<details>

```
HTTP/2 200 OK
date: Sun, 25 Apr 2021 18:15:08 GMT
server: Apache
expires: Thu, 19 Nov 1981 08:52:00 GMT
pragma: no-cache
cache-control: no-cache, no-store, must-revalidate
content-security-policy: default-src 'none';base-uri 'none';manifest-src 'self';frame-ancestors 'none'
feature-policy: autoplay 'none';camera 'none';fullscreen 'none';geolocation 'none';microphone 'none';payment 'none'
x-robots-tag: none
content-encoding: gzip
strict-transport-security: max-age=15768000
referrer-policy: no-referrer
x-content-type-options: nosniff
x-download-options: noopen
x-frame-options: SAMEORIGIN
x-permitted-cross-domain-policies: none
x-xss-protection: 1; mode=block
content-length: 106
vary: User-Agent
content-type: application/json; charset=utf-8
X-Firefox-Spdy: h2
```

</details>

**Comment by robshnup** [comment]
Hi Thomas, I don't understand this too.
I#ve an normal Nginx instance with the original recommended config by NC 21.
I've a fresh FF installation  with no old cache etc. instructions.
I get this behavoiur.
Today I've the NC 21.0.1 running and nothing is better.
I cannot produce more input on this issue than I have.
Greetz

**Comment by te-online** [comment]
@robshnup Sorry to hear. I will leave it at that for now. If you find out more or anything I can change within the app to fix it, I'm more than happy to implement it 😊
