### ISSUE TITLE
Nextcloud 27 Support

### ISSUE THREAD

**Issue by OldSmurf1** [te-online/files_linkeditor#82]
The tool does not seem to work under v27 anymore, neither can you create links nor edit them.

**Comment by te-online** [comment]
Hi @OldSmurf1 Thanks for opening this issue. I'm pinning this, because this question will probably be repeated by others.

As Nextcloud 27 has been release yesterday I will now start the process of updating the app for this version. You can expect this to take a few days or weeks, depending on the amount of adjustments needed. I'm sorry if this is not what you were hoping for. 

If you run Nextcloud in production and you subscribe to the "stable" channel you can almost always be sure that my apps will have updates available once you get prompted to update your Nextcloud.

Additionally, check for the section that tells you about app compatibility before upgrading your Nextcloud. There is a section "Apps missing compatible versions" if you have apps installed that are not compatible with the next version of Nextcloud.

![Screenshot 2023-06-14 at 20 25 13](https://github.com/te-online/files_linkeditor/assets/4127167/dc96bb42-f161-4615-8c0d-20589cbf3419)
